version: "3.8"

services:
  db:
    image: postgres:15
    container_name: insightops_db
    restart: always
    environment:
      POSTGRES_USER: insightops
      POSTGRES_PASSWORD: insightops
      POSTGRES_DB: insightops
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
